services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: health
      MYSQL_USER: health
      MYSQL_PASSWORD: health123
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql_data:/var/lib/mysql
