services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: health
      MYSQL_USER: health
      MYSQL_PASSWORD: health123
    ports:
      - "3306:3306"
    volumes:
      - ~/health_data/mysql_data:/var/lib/mysql
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - ~/health_data/minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
